version: "3"

services:
  npm:
    container_name: nginx-proxy-manager
    environment:
      - TZ=Europe/Berlin
    user: 0:1000
    networks:
      - proxy
    image: jc21/nginx-proxy-manager:latest
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    ports:
      - 80:80/tcp # HTTP
      - 443:443/tcp # HTTPS
      - 81:81/tcp # Management Dashboard
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 3s
    volumes:
      - /mnt/docker-volumes/npm/data:/data
      - /mnt/docker-volumes/npm/letsencrypt:/etc/letsencrypt

networks:
  proxy:
    external: true
